### ISSUE TITLE
ImageResizer refusing to resize several png's. Bad method for ZLIB header: cmf=126

### ISSUE THREAD

**Issue by msc2402** [VirtoCommerce/vc-module-image-tools#73]
Using the module, I am unable to convert certain png images to other resolutions. I've managed to locate the issue in the ImageService, line 36. The error that occurs is as follows:

Bad method for ZLIB header: cmf=126
at SixLabors.ImageSharp.Formats.Png.Zlib.ZlibInflateStream.InitializeInflateStream()
at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.Decode[TPixel](Stream stream)
at SixLabors.ImageSharp.Formats.Png.PngDecoder.Decode[TPixel](Configuration configuration, Stream stream)
at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)
at SixLabors.ImageSharp.Image.<>c_DisplayClass96_0`1.<Load>b_0(Stream s)
at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration config, Stream stream, Func`2 action)
at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
at SixLabors.ImageSharp.Image.Load[TPixel](Stream stream, IImageFormat& format)
at VirtoCommerce.ImageToolsModule.Data.ThumbnailGeneration.ImageService.LoadImageAsync(String imageUrl, IImageFormat& format) in C:\Projects\Heras\heras-virto\src\VirtoCommerce.Platform.Web\Modules\VirtoCommerce.ImageTools\src\VirtoCommerce.ImageToolsModule.Data\ThumbnailGeneration\ImageService.cs:line 36

One of the png's that I'm trying to convert:
https://www.dropbox.com/s/tkyarq9sbbw0hmk/D9905_Combi.png?dl=0

EDIT:

Using Module version 3.5.0

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7389 has been created

**Comment by OlegoO** [comment]
@msc2402 Could you attach (fix) the image link?
As a workaround, I recommend manually convert the image to . 

From the error, these files have been processed with an Apple-variation of https://en.wikipedia.org/wiki/Pngcrush.

I think, we can try to use PNGDecrush to decrush the image, which can then be fed to other image libraries.

E.g.:
```
using (Stream input = File.OpenRead("ff9c2b.png"))
using (MemoryStream decrushed = new MemoryStream())
{
    PNGDecrusher.Decrush(input, decrushed);
    decrushed.Position = 0;

    var image = Image.Load(decrushed);
}
````

**Comment by msc2402** [comment]
Hi Oleg,

What do you mean with fix the link? Is the image link not working for you?

Updated the initial message, added Module version 3.5.0

**Comment by OlegoO** [comment]
@msc2402 When I click, on your link https://innovadis.wetransfer.com ... , I see 404

**Comment by msc2402** [comment]
@OlegoO 
Changed the url of the image

**Comment by msc2402** [comment]
Hi Oleg,

I'm currently unable to reproduce the issue. I suspect it's something on our side yet I don't know what yet. I'll close this issue and report should I run into this again
